//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProyectItalianPizza.TestAntonio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogOut
    {
        public int IdUserEmployee { get; set; }
        public string DepartureTime { get; set; }
        public string TimeOfEntry { get; set; }
        public int IdLogOut { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
