//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTest_ItalianPizza.TestJavierBlas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stocktaking
    {
        public decimal CurrentAmount { get; set; }
        public decimal PhysicalAmount { get; set; }
        public string Description { get; set; }
        public System.DateTime Date { get; set; }
        public int IdItem { get; set; }
        public int IdStocktaking { get; set; }
    
        public virtual Item Item { get; set; }
    }
}
