//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProyectItalianPizza.TestCamarilloVilla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public Address()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public string Colony { get; set; }
        public string City { get; set; }
        public string InsideNumber { get; set; }
        public string OutsideNumber { get; set; }
        public string PostalCode { get; set; }
        public int IdCustomer { get; set; }
        public string StreetName { get; set; }
        public int IdAddresses { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
    }
}
