//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProyectItalianPizza.TestCamarilloVilla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingredient
    {
        public int IdIngredient { get; set; }
        public int IdFoodRecipe { get; set; }
        public int IdItem { get; set; }
        public string IngredientQuantity { get; set; }
        public string IngredientName { get; set; }
    
        public virtual FoodRecipe FoodRecipe { get; set; }
        public virtual Item Item { get; set; }
    }
}
