//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProyectItalianPizza.TestCamarilloVilla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provider
    {
        public Provider()
        {
            this.ProviderOrders = new HashSet<ProviderOrder>();
        }
    
        public int IdProvider { get; set; }
        public string Category { get; set; }
        public string Email { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string RFC { get; set; }
        public string Status { get; set; }
        public bool IsEnabled { get; set; }
    
        public virtual ICollection<ProviderOrder> ProviderOrders { get; set; }
    }
}
