//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTest_ItalianPizza.TestJavierBlas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuantityProviderOrder
    {
        public int IdItem { get; set; }
        public int IdProviderOrder { get; set; }
        public int QuantityOfProviderOrder { get; set; }
        public decimal Price { get; set; }
        public int IdQuantityProviderOrder { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual ProviderOrder ProviderOrder { get; set; }
    }
}
