//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProyectItalianPizza.TestCamarilloVilla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.DailyBalances = new HashSet<DailyBalance>();
            this.MonetaryExpenses = new HashSet<MonetaryExpens>();
            this.Customers = new HashSet<Customer>();
            this.LogOuts = new HashSet<LogOut>();
            this.Orders = new HashSet<Order>();
            this.ProviderOrders = new HashSet<ProviderOrder>();
            this.WorkShifts = new HashSet<WorkShift>();
        }
    
        public int IdUserEmployee { get; set; }
        public string Email { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public string Phone { get; set; }
        public string Status { get; set; }
        public System.DateTime AdmissionDate { get; set; }
        public string Password { get; set; }
        public string Role { get; set; }
        public decimal Salary { get; set; }
        public string Username { get; set; }
    
        public virtual ICollection<DailyBalance> DailyBalances { get; set; }
        public virtual ICollection<MonetaryExpens> MonetaryExpenses { get; set; }
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual ICollection<LogOut> LogOuts { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<ProviderOrder> ProviderOrders { get; set; }
        public virtual ICollection<WorkShift> WorkShifts { get; set; }
    }
}
