//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProyectItalianPizza.TestCamarilloVilla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public Item()
        {
            this.Ingredients = new HashSet<Ingredient>();
            this.QuantityItems = new HashSet<QuantityItem>();
            this.QuantityProviderOrders = new HashSet<QuantityProviderOrder>();
            this.Stocktakings = new HashSet<Stocktaking>();
        }
    
        public int IdItem { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Sku { get; set; }
        public byte[] Photo { get; set; }
        public decimal Price { get; set; }
        public int Quantity { get; set; }
        public string Restrictions { get; set; }
        public string UnitOfMeasurement { get; set; }
        public bool NeedsFoodRecipe { get; set; }
        public bool IsIngredient { get; set; }
        public bool IsEnabled { get; set; }
    
        public virtual ICollection<Ingredient> Ingredients { get; set; }
        public virtual ICollection<QuantityItem> QuantityItems { get; set; }
        public virtual ICollection<QuantityProviderOrder> QuantityProviderOrders { get; set; }
        public virtual ICollection<Stocktaking> Stocktakings { get; set; }
    }
}
